### PR TITLE
WIP: [MRESOLVER-181] Upgrade Ant to 1.9.15

### PR DESCRIPTION
**Pull request by breun**
Submitted by: Nils Breunese

o Updated to Ant 1.9.15
o Replaced use of BuildFileTest with BuildFileRule
o Integration tests are not passing yet

### CODE REVIEW

**Comment by slachiewicz** [comment]
hi, looks like issue with 1.9x version, not about test refactoring: https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven-resolver-ant-tasks/job/MRESOLVER-181/

**Comment by breun** [comment]
I see this at https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven-resolver-ant-tasks/job/MRESOLVER-181/1/console:

```
[INFO]     [junit] Testcase: warning(junit.framework.TestSuite$1):	FAILED
[INFO]     [junit] No tests found in org.apache.maven.resolver.internal.ant.ProjectWorkspaceReaderTest
[INFO]     [junit] junit.framework.AssertionFailedError: No tests found in org.apache.maven.resolver.internal.ant.ProjectWorkspaceReaderTest
```

Both my IDE and I find 3 JUnit tests in that class.

**Comment by slachiewicz** [comment]
Same on my side, if You run Maven with -X we can see more details, but I have no clue why it is not able to find JunitAdapter class

**Comment by breun** [comment]
Running `mvn -X -Prun-its verify` shows this:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.0.0:run (smoke-test) on project maven-resolver-ant-tasks: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /Users/breun/Projects/maven-resolver-ant-tasks/build.xml:98: java.lang.NoSuchMethodError: org.apache.tools.ant.util.FileUtils.createTempFile(Lorg/apache/tools/ant/Project;Ljava/lang/String;Ljava/lang/String;Ljava/io/File;ZZ)Ljava/io/File;
[ERROR] around Ant part ...<ant antfile="build.xml" />... @ 4:32 in /Users/breun/Projects/maven-resolver-ant-tasks/target/antrun/build-main.xml
```

I'm afraid I don't know what code is trying to execute `FileUtils.createTempFile(Project, String, String, File)`, but Ant 1.9.15's `FileUtils` indeed only has these `createTempFile` methods:

* `public File createTempFile(final Project project, String prefix, String suffix, final File parentDir, final boolean deleteOnExit, final boolean createFile)`
* `public File createTempFile(String prefix, String suffix, File parentDir)` (deprecated "since ant 1.7.1 use createTempFile(Project, String, String, File, boolean, boolean) instead")
* `public File createTempFile(String prefix, String suffix, File parentDir, boolean deleteOnExit, boolean createFile)` (deprecated "since Ant 1.9.15 use createTempFile(Project, String, String, File, boolean, boolean) instead")
* `public File createTempFile(String prefix, String suffix, File parentDir, boolean deleteOnExit)` (deprecated "since ant 1.7.1 use createTempFile(Project, String, String, File, boolean, boolean) instead")

**Comment by michael-o** [comment]
@breun I can confirm this, sadly. I guess one needs to debug this.

**Comment by michael-o** [comment]
I am currently stuck at:
```
[INFO]     [junit] Testsuite: org.apache.maven.resolver.internal.ant.DeployTest
[INFO]     [junit] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0,005 sec
[INFO]     [junit] 
[INFO]     [junit] Testcase: warning(junit.framework.TestSuite$1):	FAILED
[INFO]     [junit] No tests found in org.apache.maven.resolver.internal.ant.DeployTest
[INFO]     [junit] junit.framework.AssertionFailedError: No tests found in org.apache.maven.resolver.internal.ant.DeployTest
[INFO]     [junit] 
[INFO]     [junit] 
[DEBUG]       [ant] Exiting D:\Entwicklung\Projekte\maven-resolver-ant-tasks\build.xml.
```

**Comment by michael-o** [comment]
Tried for two more hours, no avail. I don't see the actual issue here :-(
If you run Ant directly, it works, but the locks up with the `ResolveTest` :-(

**Comment by michael-o** [comment]
I am included to disable this test for now and continue with the PR until someone can solve this.

**Comment by cstamas** [comment]
To me also it runs all until ResolveTest where it deadlocks, Reason is:
1- DefaultAntLogger uses PrintStream (that sync on this/self)
2- AntBuildsTest now uses BuildFileRule that in turn executes all the goals withing synchronized block (on system out)
3- resolver by default resolve on MT

Simply put: test is nested in such way, that multi threaded logging will deadlock, and resolver by default does exactly that

**Comment by cstamas** [comment]
Pushed changes I did (partially based on changes in this PR), please reuse https://github.com/apache/maven-resolver-ant-tasks/pull/13

**Comment by jira-importer** [comment]
Resolve #89

**Pull request closed without merging**
